### ISSUE TITLE
图片不能显示

### ISSUE THREAD

**Issue by benja956** [xiaoqiangjun/gugubot#2]
将网络图片(url)和本地图片(物理地址)作为pic上传均不能在微博正常显示图片。
另外，datetime.datetime中fromisoformat属性为python3.7以及以上版本才有，python3.7以下版本没有。

**Comment by xiaoqiangjun** [comment]
1. 不能正常显示是什么情况，有没有上传成功呢
2. 谢谢你的提醒，我的问题，解决图片问题会一起提交

**Comment by benja956** [comment]
感谢您的回复，我的返回和参数设置如下。将微博设置为公开和私人均不能展示图片。
D:\auto_wb\venv\Scripts\python.exe D:/projects/gugubot-main/gugubot-main/weibo.py
08/16 22:36:12 - login229 - INFO - 从文件中恢复Cookie成功，跳过登录。
08/16 22:36:12 - login258 - INFO - 成功使用cookies登录
08/16 22:36:12 - login267 - INFO - 新的Cookie已保存。
08/16 22:36:13 - weibo132 - INFO - 图片上传成功。pid:6iJVUMgy1gtj08iemdnj60h80bc76g02
08/16 22:36:13 - weibo116 - INFO - 共有1张图片，成功上传1张图片
08/16 22:36:13 - weibo64 - INFO - 定时微博设置成功，时间为: 2021-08-16 22:38:00
08/16 22:36:13 - weibo67 - INFO - 内容为：test

```
    weibo = Weibo(username,password,ocr_token,cookies_flag)
    weibo.weibo_login()
    pic = weibo.get_picid(["http://pic.imgii.com/wp-content/uploads/2014/03/20140228024121418.jpg"])
    times = weibo.get_intime("2021-08-16 22:38:00")
    weibo.post_weibo("test",intime=times,pic=pic,rank=1)
```

**Comment by xiaoqiangjun** [comment]
我这里测试是正常的，看你没有报错应该也没问题啊，是否是设置的定时时间问题，时间没到？这里可以看到定时微博&nbsp;https://weibo.com/manage/schedule?type=0
或者你去掉定时的语句试一下呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 晚上10:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaoqiangjun/gugubot] 图片不能显示 (#2)





 
感谢您的回复，我的返回和参数设置如下。将微博设置为公开和私人均不能展示图片。
 D:\auto_wb\venv\Scripts\python.exe D:/projects/gugubot-main/gugubot-main/weibo.py
 08/16 22:36:12 - login229 - INFO - 从文件中恢复Cookie成功，跳过登录。
 08/16 22:36:12 - login258 - INFO - 成功使用cookies登录
 08/16 22:36:12 - login267 - INFO - 新的Cookie已保存。
 08/16 22:36:13 - weibo132 - INFO - 图片上传成功。pid:6iJVUMgy1gtj08iemdnj60h80bc76g02
 08/16 22:36:13 - weibo116 - INFO - 共有1张图片，成功上传1张图片
 08/16 22:36:13 - weibo64 - INFO - 定时微博设置成功，时间为: 2021-08-16 22:38:00
 08/16 22:36:13 - weibo67 - INFO - 内容为：test
     weibo = Weibo(username,password,ocr_token,cookies_flag)     weibo.weibo_login()     pic = weibo.get_picid(["http://pic.imgii.com/wp-content/uploads/2014/03/20140228024121418.jpg"])     times = weibo.get_intime("2021-08-16 22:38:00")     weibo.post_weibo("test",intime=times,pic=pic,rank=1)  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benja956** [comment]
经测试，只有进行实名并绑定手机号的微博号，才能使用本通道进行图片发布。没有绑定手机的号，带图会裂开。我现在也裂开了

**Comment by xiaoqiangjun** [comment]
啊这，非常抱歉我完全没考虑到这个问题，感谢你的测试，我会在readme上更新这个注意事项的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月17日(周二) 凌晨1:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaoqiangjun/gugubot] 图片不能显示 (#2)




 
经测试，只有进行实名并绑定手机号的微博号，才能使用本通道进行图片发布。没有绑定手机的号，带图会裂开。我现在也裂开了
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ting1e** [comment]
> 啊这，非常抱歉我完全没考虑到这个问题，感谢你的测试，我会在readme上更新这个注意事项的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年8月17日(周二) 凌晨1:03 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xiaoqiangjun/gugubot] 图片不能显示 (#2) 经测试，只有进行实名并绑定手机号的微博号，才能使用本通道进行图片发布。没有绑定手机的号，带图会裂开。我现在也裂开了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

这个是获取图片pid的问题，图片pid前面可能会多出00

开头加上 

    from json import loads

获取图片pid，改成这样就好了，

     def upload_pic(self, file):
        """
        description: 上传图片到微博，非新版微博使用接口
        param bytes-like file 待上传图片数据
        return str pid 微博图片id
        """

        url = 'https://picupload.weibo.com/interface/pic_upload.php?data=base64'
        data = {'b64_data': b64encode(file)}
        response = self.sess.post(url=url, data=data).text

        js = loads(response[response.find('{'):])
        if 'A00006' == js['code']:
            pid = js['data']['pics']['pic_1']['pid']
            logging.info('图片上传成功。pid:%s' % pid)
            return pid
        else:
            logging.warning('图片上传失败。')
        sleep(self.post_delay)

**Comment by benja956** [comment]
> > 啊这，非常抱歉我完全没考虑到这个问题，感谢你的测试，我会在readme上更新这个注意事项的
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2021年8月17日(周二) 凌晨1:03 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [xiaoqiangjun/gugubot] 图片不能显示 (#2) 经测试，只有进行实名并绑定手机号的微博号，才能使用本通道进行图片发布。没有绑定手机的号，带图会裂开。我现在也裂开了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> 这个是获取图片pid的问题，图片pid前面可能会多出00
> 
> 开头加上
> 
> ```
> from json import loads
> ```
> 
> 获取图片pid，改成这样就好了，
> 
> ```
>  def upload_pic(self, file):
>     """
>     description: 上传图片到微博，非新版微博使用接口
>     param bytes-like file 待上传图片数据
>     return str pid 微博图片id
>     """
> 
>     url = 'https://picupload.weibo.com/interface/pic_upload.php?data=base64'
>     data = {'b64_data': b64encode(file)}
>     response = self.sess.post(url=url, data=data).text
> 
>     js = loads(response[response.find('{'):])
>     if 'A00006' == js['code']:
>         pid = js['data']['pics']['pic_1']['pid']
>         logging.info('图片上传成功。pid:%s' % pid)
>         return pid
>     else:
>         logging.warning('图片上传失败。')
>     sleep(self.post_delay)
> ```

感谢您的建议，我使用此代码成功运行了数次，但今天报错：json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)。这貌似是由于接口变化所导致的，请问您有遇到这样的情况吗？

**Comment by benja956** [comment]
> > > 啊这，非常抱歉我完全没考虑到这个问题，感谢你的测试，我会在readme上更新这个注意事项的
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2021年8月17日(周二) 凌晨1:03 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [xiaoqiangjun/gugubot] 图片不能显示 (#2) 经测试，只有进行实名并绑定手机号的微博号，才能使用本通道进行图片发布。没有绑定手机的号，带图会裂开。我现在也裂开了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> > 
> > 
> > 这个是获取图片pid的问题，图片pid前面可能会多出00
> > 开头加上
> > ```
> > from json import loads
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 获取图片pid，改成这样就好了，
> > ```
> >  def upload_pic(self, file):
> >     """
> >     description: 上传图片到微博，非新版微博使用接口
> >     param bytes-like file 待上传图片数据
> >     return str pid 微博图片id
> >     """
> > 
> >     url = 'https://picupload.weibo.com/interface/pic_upload.php?data=base64'
> >     data = {'b64_data': b64encode(file)}
> >     response = self.sess.post(url=url, data=data).text
> > 
> >     js = loads(response[response.find('{'):])
> >     if 'A00006' == js['code']:
> >         pid = js['data']['pics']['pic_1']['pid']
> >         logging.info('图片上传成功。pid:%s' % pid)
> >         return pid
> >     else:
> >         logging.warning('图片上传失败。')
> >     sleep(self.post_delay)
> > ```
> 
> 感谢您的建议，我使用此代码成功运行了数次，但今天报错：json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)。这貌似是由于接口变化所导致的，请问您有遇到这样的情况吗？

好像虽然会报错，但依旧执行了定时任务
